import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import poster from "../../public/poster.png";
import coffee from "../../public/coffee.png";
import bezelLeft from "../../public/bezel-left.png";
import bezelRight from "../../public/bezel-right.png";
import screenLeft from "../../public/screen-left.png";
import screenRight from "../../public/screen-right.png";
import screenTop from "../../public/screen-top.png";
import screenBottom from "../../public/screen-bottom.png";
import clonex from "../../public/clonex12118.png";
import driveEmpty from "../../public/drive-empty.png";
import driveFull from "../../public/drive-full.png";

const Home: NextPage = () => {
  const [isConnected, setIsConnected] = useState(false);
  return (
    <>
      <Head>
        <title>HODLHQ Terminal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative z-0 flex h-screen flex-col items-center justify-center bg-[#fefae1]">
        <div
          className="absolute inset-x-0 bottom-0 z-10 h-1/6 max-h-[346px] w-[100%] overflow-hidden bg-repeat-x"
          style={{ backgroundImage: "url(/desk.png)" }}
        >
          {" "}
        </div>
        <Image
          src={poster}
          alt=""
          className="max-h-1/2 absolute top-0 right-0 z-10 float-right h-1/2 object-contain object-right"
        />
        <div className="z-20 flex h-screen flex-row justify-center md:container">
          <Image src={bezelLeft} alt="" className="h-full max-w-[40px]" />
          <div className="w-[88px] bg-[#dfd6c1]"> </div>
          <div className="grow bg-[#dfd6c1] pt-[8px]">
            <div className="flex flex-row justify-center">
              <div className="max-w-[35px] bg-[#cccccc]">
                <Image src={screenLeft} alt="" className="h-full" />
              </div>
              <div className="flex flex-col items-stretch bg-[#cccccc]">
                <Image
                  src={screenTop}
                  alt=""
                  className="h-[55px] overflow-hidden"
                />
                <div className="relative grow">
                  <div className="flex justify-center">
                    <div className="flex flex-col rounded-lg bg-white shadow-lg sm:max-w-xl sm:flex-row">
                      <Image
                        className=" h-96 w-full rounded-t-lg object-cover sm:h-auto sm:w-48 sm:rounded-none sm:rounded-l-lg"
                        src={clonex}
                        alt=""
                      />
                      <div className="flex flex-col justify-start p-6">
                        <h5 className="mb-2 text-xl font-medium text-gray-900">
                          CloneX 12118
                        </h5>
                        <p className="mb-4 text-base text-gray-700">
                          Download 3D files
                        </p>
                        <p className="text-xs text-gray-600">
                          Last updated 3 mins ago
                        </p>
                        <button
                          type="button"
                          className=" inline-block rounded bg-blue-600 px-6 py-2.5 text-xs font-medium uppercase leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg"
                        >
                          3D Files
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <Image
                  src={screenBottom}
                  alt=""
                  className="h-[132px] overflow-hidden"
                />
              </div>
              <div className="max-w-[35px] bg-[#cccccc]">
                <Image
                  src={screenRight}
                  alt=""
                  className="h-full max-w-[35px]"
                />
              </div>
            </div>
            <div
              className="max-h-[76px] w-1/2 bg-[#dfd6c1] p-4"
              onClick={() => setIsConnected(!Boolean(isConnected))}
            >
              <Image
                src={isConnected ? driveEmpty : driveFull}
                className="h-[76px]"
                alt=""
              />
            </div>
          </div>
          <div className="w-[88px] bg-[#dfd6c1]"> </div>
          <Image src={bezelRight} className="h-full max-w-[40px]" alt="" />
        </div>
        <Image
          src={coffee}
          alt=""
          className="invisible absolute bottom-0 left-0 z-30 float-left h-1/5 object-contain object-left md:visible"
        />
      </main>
    </>
  );
};

export default Home;
